name: Rust format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@master
        with:
          args: cd integration-test && cargo fmt -- --check
          # TODO: check Clippy too after fixing all the warnings
          # args: cd integration-test && cargo fmt -- --check && cargo clippy -- -Dwarnings
